// ==UserScript==
// @name         Song Tracker for OS!
// @match    https://onlinesequencer.net/forum/chat_frame.php?ez_iframe=1
// @version      2024-02-23
// @description  Music is nice.
// @author       You
// @icon         https://www.google.com/s2/favicons?sz=64&domain=tampermonkey.net
// @grant        none
// @run-at document-start
// ==/UserScript==
function addToPlaylist(id, sequenceId){
    let settings = {
    "domain": "https://onlinesequencer.net",
    "template": "default",
    "instruments": [
        "Elec. Piano (Classic)",
        "Acoustic Guitar",
        "Drum Kit",
        "Smooth Synth (Classic)",
        "Electric Guitar",
        "Bass Guitar (Classic)",
        "Synth Pluck",
        "Scifi",
        "Grand Piano (Classic)",
        "French Horn",
        "Trombone",
        "Violin",
        "Cello",
        "8-Bit Sine",
        "8-Bit Square",
        "8-Bit Sawtooth",
        "8-Bit Triangle",
        "Harpsichord",
        "Concert Harp",
        "Xylophone",
        "Pizzicato",
        "Steel Drums",
        "Sitar",
        "Flute",
        "Saxophone",
        "Ragtime Piano",
        "Music Box",
        "Synth Bass (Classic)",
        "Church Organ",
        "Slap Bass",
        "Pop Synth (Classic)",
        "Electric Drum Kit",
        "Jazz Guitar",
        "Koto",
        "Vibraphone",
        "Muted E-Guitar",
        "808 Drum Kit",
        "808 Bass",
        "Distortion Guitar",
        "8-Bit Drum Kit",
        "2013 Drum Kit",
        "Grand Piano",
        "909 Drum Kit",
        "Electric Piano",
        "Dist. Guitar (Sustain)",
        "Cello (Sustain)",
        "Violin (Sustain)",
        "Strings (Sustain)",
        "Bass",
        "Clean Guitar",
        "French Horn (Sustain)",
        "Trombone (Sustain)",
        "Smooth Synth",
        "2023 Drum Kit",
        "Bass Guitar",
        "custom synth :DDDD",
        "Synth Bass (Sustain)",
        "Pop Synth (Sustain)"
    ],
    "fadeTimes": {
        "4": 0.01,
        "23": 0.01,
        "44": 0.2,
        "49": 0.2,
        "50": 0.5,
        "51": 0.5,
        "52": 2.5,
        "53": 0.1,
        "54": 0.2,
        "56": 0.2,
        "57": 0.2
    },
    "min": [
        0,
        0,
        3,
        0,
        0,
        0,
        0,
        12,
        0,
        16,
        16,
        31,
        12,
        0,
        0,
        0,
        0,
        7,
        12,
        31,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3,
        0,
        0,
        0,
        7,
        3,
        7,
        7,
        7,
        7,
        0,
        3,
        0,
        12,
        12,
        31,
        0,
        4,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
    ],
    "max": [
        71,
        59,
        63,
        59,
        59,
        35,
        59,
        71,
        71,
        47,
        55,
        70,
        48,
        71,
        71,
        71,
        71,
        65,
        59,
        70,
        71,
        71,
        71,
        71,
        71,
        71,
        71,
        71,
        71,
        67,
        71,
        63,
        59,
        71,
        71,
        59,
        20,
        28,
        62,
        12,
        34,
        71,
        22,
        71,
        62,
        48,
        70,
        71,
        37,
        64,
        59,
        59,
        71,
        71,
        35,
        0,
        71,
        71
    ],
    "originalBpm": [
        30,
        15,
        10,
        20,
        30,
        20,
        20,
        20,
        15,
        30,
        30,
        40,
        40,
        0,
        0,
        0,
        0,
        30,
        10,
        25,
        20,
        30,
        20,
        20,
        30,
        30,
        20,
        20,
        10,
        20,
        20,
        20,
        20,
        30,
        20,
        20,
        10,
        10,
        10,
        20,
        16.26,
        0,
        30,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        6,
        0,
        0,
        0,
        0
    ],
    "volume": [
        0.25,
        0.5,
        0.4,
        0.8,
        0.8,
        0.8,
        0.65,
        0.8,
        0.3,
        0.2,
        0.2,
        0.55,
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.3,
        0.3,
        0.3,
        1.3,
        1.3,
        1.5,
        1,
        1,
        1.5,
        1.5,
        1,
        1,
        1,
        1,
        0.8,
        1,
        1.3,
        1,
        1,
        1,
        0.5,
        1,
        1,
        1,
        0.4,
        2.8,
        0.18,
        0.3,
        1,
        0.55,
        1,
        0.6,
        0.4,
        0.5,
        0.5,
        0.8,
        0.8,
        0.8,
        0,
        0.3,
        0.3
    ],
    "midiInstrumentMap": [
        1,
        25,
        1,
        81,
        30,
        33,
        88,
        100,
        1,
        61,
        58,
        41,
        43,
        83,
        81,
        82,
        88,
        7,
        46,
        14,
        46,
        115,
        105,
        74,
        65,
        4,
        11,
        39,
        20,
        37,
        51,
        1,
        27,
        108,
        12,
        29,
        1,
        1,
        31,
        1,
        1,
        1,
        1,
        1,
        43,
        43,
        41,
        44,
        33,
        28,
        61,
        58,
        81,
        1,
        33,
        0,
        39,
        51
    ],
    "audioVersion": 20,
    "instrumentCloneOffset": 10000,
    "volumeWeights": [
        1,
        0.7692,
        {
            "D#7": 0.6667,
            "D7": 0.5882,
            "C#7": 0.5,
            "C7": 0.5,
            "B6": 0.6667,
            "A#6": 0.6667,
            "A6": 0.7692,
            "G#6": 0.5714,
            "G6": 0.5,
            "F#6": 0.5,
            "F6": 0.5,
            "E6": 0.5,
            "D#6": 0.5882,
            "D6": 0.625,
            "C#6": 0.625,
            "C6": 0.8333,
            "B5": 0.7692,
            "A#5": 0.5882,
            "A5": 0.6667,
            "G#5": 0.625,
            "G5": 0.625,
            "F#5": 0.6667,
            "F5": 0.6667,
            "E5": 0.5,
            "D#5": 0.5,
            "D5": 0.5,
            "C#5": 0.5263,
            "C5": 0.5,
            "B4": 0.625,
            "A#4": 0.6667,
            "A4": 0.8333,
            "G#4": 0.6667,
            "G4": 0.7143,
            "F#4": 0.6667,
            "F4": 0.7143,
            "E4": 1,
            "D#4": 0.5882,
            "D4": 0.5,
            "C#4": 1,
            "C4": 0.7143,
            "B3": 0.625,
            "A#3": 1,
            "A3": 0.5882,
            "G#3": 0.5,
            "G3": 0.5,
            "F#3": 0.5556,
            "F3": 0.5556,
            "E3": 0.7143,
            "D#3": 0.8333,
            "D3": 0.625,
            "C#3": 0.625,
            "C3": 0.5,
            "B2": 0.5,
            "A#2": 0.7692,
            "A2": 0.5,
            "G#2": 0.5,
            "G2": 0.5882,
            "F#2": 0.5882,
            "F2": 0.6667,
            "E2": 0.8333,
            "D#2": 0.5
        },
        1.25,
        1.25,
        1,
        0.9091,
        1.25,
        1,
        1,
        1.25,
        1,
        0.5882,
        0.7143,
        1.4286,
        1.1111,
        0.7692,
        1.25,
        0.625,
        1,
        0.8333,
        0.9091,
        1.1765,
        0.6667,
        1,
        1,
        0.8696,
        1,
        0.625,
        1.1111,
        1.1111,
        {
            "D#7": 0.625,
            "D7": 0.6667,
            "C#7": 0.7143,
            "C7": 1.3333,
            "B6": 1.3333,
            "A#6": 1.25,
            "A6": 1.25,
            "G#6": 1,
            "G6": 0.6667,
            "F#6": 0.6897,
            "F6": 0.5,
            "E6": 0.5,
            "D#6": 1,
            "D6": 1.25,
            "C#6": 0.8333,
            "C6": 1.25,
            "B5": 1.2,
            "A#5": 0.7692,
            "A5": 0.8696,
            "G#5": 0.7692,
            "G5": 0.7407,
            "F#5": 0.8,
            "F5": 0.7407,
            "E5": 0.5882,
            "D#5": 0.5,
            "D5": 0.625,
            "C#5": 0.5263,
            "C5": 0.625,
            "B4": 0.9524,
            "A#4": 1.4286,
            "A4": 1.4286,
            "G#4": 0.9524,
            "G4": 0.8,
            "F#4": 0.6667,
            "F4": 0.6667,
            "E4": 1.0526,
            "D#4": 0.6667,
            "D4": 0.7692,
            "C#4": 1,
            "C4": 0.9524,
            "B3": 1,
            "A#3": 1.3333,
            "A3": 1.1111,
            "G#3": 0.9091,
            "G3": 0.7143,
            "F#3": 0.4545,
            "F3": 0.7692,
            "E3": 1,
            "D#3": 1.5385,
            "D3": 1,
            "C#3": 0.6897,
            "C3": 0.9091,
            "B2": 0.9091,
            "A#2": 0.8,
            "A2": 0.5,
            "G#2": 0.4,
            "G2": 0.9091,
            "F#2": 1,
            "F2": 1,
            "E2": 0.625,
            "D#2": 0.8
        },
        0.9091,
        1.25,
        1.1765,
        1.3333,
        {
            "G#3": 2,
            "G3": 4,
            "F#3": 3.5714,
            "F3": 1.4286,
            "E3": 1.4286,
            "D#3": 1.6667,
            "D3": 1.6667,
            "C#3": 2.2222,
            "C3": 4,
            "B2": 2.8571,
            "A#2": 1.6667,
            "A2": 2,
            "G#2": 2.5,
            "G2": 4,
            "F#2": 2.8571,
            "F2": 1.5385,
            "E2": 1,
            "D#2": 1
        },
        1.25,
        1.1111,
        {
            "C3": 2.5,
            "B2": 1.8182,
            "A#2": 1.8182,
            "A2": 0.8333,
            "G#2": 1,
            "G2": 1.25
        },
        {
            "A#4": 1.6667,
            "A4": 3.3333,
            "G#4": 2.5,
            "G4": 2.5,
            "F#4": 0.25,
            "F4": 2.5,
            "E4": 2.5,
            "D#4": 2.5,
            "D4": 2.5,
            "C#4": 2,
            "C4": 2.8571,
            "B3": 1.25,
            "A#3": 1.5385,
            "A3": 2.5,
            "G#3": 2.2222,
            "G3": 1.4286,
            "F#3": 0.9091,
            "F3": 2.5,
            "E3": 1.3333,
            "D#3": 1.6667,
            "D3": 1.1111,
            "C#3": 1.5385,
            "C3": 2.2222,
            "B2": 3.6364,
            "A#2": 4,
            "A2": 2.5,
            "G#2": 2.5,
            "G2": 1.6667
        },
        0.9524,
        {
            "A#3": 0.9524,
            "A3": 1.6667,
            "G#3": 1.5385,
            "G3": 1.5385,
            "F#3": 1.25,
            "F3": 0.8696,
            "E3": 1.6667,
            "D#3": 1.25,
            "D3": 1.1111,
            "C#3": 0.8696,
            "C3": 0.8333,
            "B2": 0.7407,
            "A#2": 0.9091,
            "A2": 0.7692,
            "G#2": 1.5385,
            "G2": 2,
            "F#2": 2,
            "F2": 1.8182,
            "E2": 1.8182,
            "D#2": 1.8182
        },
        0.9524,
        0.9524,
        0.9524,
        1,
        1,
        1,
        1,
        1,
        1.25,
        1.25,
        1,
        1,
        0,
        1,
        1.1111
    ],
    "instrumentCategories": {
        "Piano": [
            43,
            41,
            17,
            25,
            26,
            0,
            8
        ],
        "Percussion (MIDI)": [
            2,
            31,
            19,
            34,
            21
        ],
        "Percussion (Classic)": [
            39,
            40,
            36,
            42,
            53
        ],
        "Guitar": [
            1,
            4,
            48,
            54,
            5,
            29,
            32,
            35,
            38,
            44,
            49,
            22,
            33
        ],
        "Electronic": [
            52,
            6,
            7,
            13,
            14,
            15,
            16,
            30,
            57,
            27,
            56,
            37
        ],
        "Orchestra": [
            9,
            50,
            10,
            51,
            11,
            46,
            12,
            45,
            18,
            20,
            23,
            47,
            24,
            28
        ]
    },
    "instrumentCategoryIcons": {
        "Piano": "<i class=\"fas fa-piano-keyboard\"></i>",
        "Percussion (MIDI)": "<i class=\"fas fa-drum\"></i>",
        "Percussion (Classic)": "<i class=\"fas fa-drum\"></i>",
        "Guitar": "<i class=\"fas fa-guitar\"></i>",
        "Electronic": "<i class=\"fas fa-alien-monster\"></i>",
        "Orchestra": "<i class=\"fas fa-trumpet\"></i>",
        "Testing": "<i class=\"fas fa-flask\"></i>"
    },
    "instrumentColors": [
        [
            255,
            3,
            169,
            244
        ],
        [
            255,
            255,
            152,
            0
        ],
        [
            255,
            183,
            28,
            28
        ],
        [
            255,
            233,
            30,
            99
        ],
        [
            255,
            76,
            175,
            80
        ],
        [
            255,
            33,
            33,
            33
        ],
        [
            255,
            63,
            81,
            181
        ],
        [
            255,
            205,
            220,
            57
        ],
        [
            255,
            21,
            101,
            192
        ],
        [
            255,
            130,
            119,
            23
        ],
        [
            255,
            255,
            234,
            0
        ],
        [
            255,
            141,
            110,
            99
        ],
        [
            255,
            78,
            52,
            46
        ],
        [
            255,
            255,
            99,
            99
        ],
        [
            255,
            117,
            255,
            99
        ],
        [
            255,
            99,
            224,
            255
        ],
        [
            255,
            253,
            99,
            255
        ],
        [
            255,
            255,
            87,
            34
        ],
        [
            255,
            27,
            94,
            32
        ],
        [
            255,
            244,
            67,
            54
        ],
        [
            255,
            255,
            224,
            178
        ],
        [
            255,
            117,
            117,
            117
        ],
        [
            255,
            224,
            173,
            0
        ],
        [
            255,
            233,
            249,
            189
        ],
        [
            255,
            168,
            200,
            83
        ],
        [
            255,
            13,
            71,
            161
        ],
        [
            255,
            29,
            157,
            157
        ],
        [
            255,
            30,
            197,
            122
        ],
        [
            255,
            21,
            33,
            79
        ],
        [
            255,
            5,
            16,
            47
        ],
        [
            255,
            108,
            243,
            183
        ],
        [
            255,
            255,
            112,
            112
        ],
        [
            255,
            161,
            166,
            53
        ],
        [
            255,
            234,
            121,
            0
        ],
        [
            255,
            85,
            202,
            202
        ],
        [
            255,
            0,
            128,
            64
        ],
        [
            255,
            127,
            15,
            72
        ],
        [
            255,
            0,
            0,
            0
        ],
        [
            255,
            0,
            69,
            31
        ],
        [
            255,
            159,
            15,
            34
        ],
        [
            255,
            130,
            5,
            21
        ],
        [
            255,
            21,
            101,
            192
        ],
        [
            255,
            152,
            0,
            254
        ],
        [
            255,
            3,
            169,
            244
        ],
        [
            255,
            0,
            69,
            31
        ],
        [
            255,
            78,
            52,
            46
        ],
        [
            255,
            141,
            110,
            99
        ],
        [
            255,
            142,
            118,
            255
        ],
        [
            255,
            33,
            33,
            33
        ],
        [
            255,
            224,
            211,
            24
        ],
        [
            255,
            130,
            119,
            23
        ],
        [
            255,
            255,
            234,
            0
        ],
        [
            255,
            233,
            30,
            99
        ],
        [
            255,
            113,
            0,
            166
        ],
        [
            255,
            33,
            33,
            33
        ],
        [
            255,
            255,
            255,
            255
        ],
        [
            255,
            30,
            197,
            122
        ],
        [
            255,
            108,
            243,
            183
        ]
    ],
    "typingKeyboard": [
        "zxcvbnm,./",
        "asdfghjkl;'",
        "qwertyuiop[]"
    ],
    "punctuationCodes": {
        "BracketLeft": "[",
        "BracketRight": "]",
        "Backslash": "\\",
        "Semicolon": ";",
        "Quote": "'",
        "Comma": ",",
        "Period": ".",
        "Slash": "/"
    },
    "clipboardMagicString": "Online Sequencer",
    "piano": [
        "C2",
        "C#2",
        "D2",
        "D#2",
        "E2",
        "F2",
        "F#2",
        "G2",
        "G#2",
        "A2",
        "A#2",
        "B2",
        "C3",
        "C#3",
        "D3",
        "D#3",
        "E3",
        "F3",
        "F#3",
        "G3",
        "G#3",
        "A3",
        "A#3",
        "B3",
        "C4",
        "C#4",
        "D4",
        "D#4",
        "E4",
        "F4",
        "F#4",
        "G4",
        "G#4",
        "A4",
        "A#4",
        "B4",
        "C5",
        "C#5",
        "D5",
        "D#5",
        "E5",
        "F5",
        "F#5",
        "G5",
        "G#5",
        "A5",
        "A#5",
        "B5",
        "C6",
        "C#6",
        "D6",
        "D#6",
        "E6",
        "F6",
        "F#6",
        "G6",
        "G#6",
        "A6",
        "A#6",
        "B6",
        "C7",
        "C#7",
        "D7",
        "D#7",
        "E7",
        "F7",
        "F#7",
        "G7",
        "G#7",
        "A7",
        "A#7",
        "B7"
    ],
    "pianoNotes": [
        "C",
        "C#",
        "D",
        "D#",
        "E",
        "F",
        "F#",
        "G",
        "G#",
        "A",
        "A#",
        "B"
    ],
    "scaleNames": [
        "No Key Guide",
        "C Major",
        "C# Major",
        "D Major",
        "D# Major",
        "E Major",
        "F Major",
        "F# Major",
        "G Major",
        "G# Major",
        "A Major",
        "A# Major",
        "B Major",
        "C Minor",
        "C# Minor",
        "D Minor",
        "D# Minor",
        "E Minor",
        "F Minor",
        "F# Minor",
        "G Minor",
        "G# Minor",
        "A Minor",
        "A# Minor",
        "B Minor"
    ],
    "scaleOctaves": [
        0,
        6,
        5,
        5,
        4,
        4,
        3,
        3,
        2,
        1,
        1,
        0,
        0,
        6,
        6,
        5,
        5,
        4,
        3,
        3,
        2,
        2,
        1,
        0,
        0
    ],
    "scales": [
        [],
        [
            "C",
            "D",
            "E",
            "F",
            "G",
            "A",
            "B",
            "C",
            "D",
            "E",
            "F",
            "G"
        ],
        [
            "C#",
            "D#",
            "F",
            "F#",
            "G#",
            "A#",
            "C",
            "C#",
            "D#",
            "F",
            "F#",
            "G#"
        ],
        [
            "D",
            "E",
            "F#",
            "G",
            "A",
            "B",
            "C#",
            "D",
            "E",
            "F#",
            "G",
            "A"
        ],
        [
            "D#",
            "F",
            "G",
            "G#",
            "A#",
            "C",
            "D",
            "D#",
            "F",
            "G",
            "G#",
            "A#"
        ],
        [
            "E",
            "F#",
            "G#",
            "A",
            "B",
            "C#",
            "D#",
            "E",
            "F#",
            "G#",
            "A",
            "B"
        ],
        [
            "F",
            "G",
            "A",
            "A#",
            "C",
            "D",
            "E",
            "F",
            "G",
            "A",
            "A#",
            "C"
        ],
        [
            "F#",
            "G#",
            "A#",
            "B",
            "C#",
            "D#",
            "F",
            "F#",
            "G#",
            "A#",
            "B",
            "C#"
        ],
        [
            "G",
            "A",
            "B",
            "C",
            "D",
            "E",
            "F#",
            "G",
            "A",
            "B",
            "C",
            "D"
        ],
        [
            "G#",
            "A#",
            "C",
            "C#",
            "D#",
            "F",
            "G",
            "G#",
            "A#",
            "C",
            "C#",
            "D#"
        ],
        [
            "A",
            "B",
            "C#",
            "D",
            "E",
            "F#",
            "G#",
            "A",
            "B",
            "C#",
            "D",
            "E"
        ],
        [
            "A#",
            "C",
            "D",
            "D#",
            "F",
            "G",
            "A",
            "A#",
            "C",
            "D",
            "D#",
            "F"
        ],
        [
            "B",
            "C#",
            "D#",
            "E",
            "F#",
            "G#",
            "A#",
            "B",
            "C#",
            "D#",
            "E",
            "F#"
        ],
        [
            "C",
            "D",
            "D#",
            "F",
            "G",
            "G#",
            "A#",
            "C",
            "D",
            "D#",
            "F",
            "G"
        ],
        [
            "C#",
            "D#",
            "E",
            "F#",
            "G#",
            "A",
            "B",
            "C#",
            "D#",
            "E",
            "F#",
            "G#"
        ],
        [
            "D",
            "E",
            "F",
            "G",
            "A",
            "A#",
            "C",
            "D",
            "E",
            "F",
            "G",
            "A"
        ],
        [
            "D#",
            "F",
            "F#",
            "G#",
            "A#",
            "B",
            "C#",
            "D#",
            "F",
            "F#",
            "G#",
            "A#"
        ],
        [
            "E",
            "F#",
            "G",
            "A",
            "B",
            "C",
            "D",
            "E",
            "F#",
            "G",
            "A",
            "B"
        ],
        [
            "F",
            "G",
            "G#",
            "A#",
            "C",
            "C#",
            "D#",
            "F",
            "G",
            "G#",
            "A#",
            "C"
        ],
        [
            "F#",
            "G#",
            "A",
            "B",
            "C#",
            "D",
            "E",
            "F#",
            "G#",
            "A",
            "B",
            "C#"
        ],
        [
            "G",
            "A",
            "A#",
            "C",
            "D",
            "D#",
            "F",
            "G",
            "A",
            "A#",
            "C",
            "D"
        ],
        [
            "G#",
            "A#",
            "B",
            "C#",
            "D#",
            "E",
            "F#",
            "G#",
            "A#",
            "B",
            "C#",
            "D#"
        ],
        [
            "A",
            "B",
            "C",
            "D",
            "E",
            "F",
            "G",
            "A",
            "B",
            "C",
            "D",
            "E"
        ],
        [
            "A#",
            "C",
            "C#",
            "D#",
            "F",
            "F#",
            "G#",
            "A#",
            "C",
            "C#",
            "D#",
            "F"
        ],
        [
            "B",
            "C#",
            "D",
            "E",
            "F#",
            "G",
            "A",
            "B",
            "C#",
            "D",
            "E",
            "F#"
        ]
    ],
    "percussion": [
        "Open Surdo",
        "Closed Surdo",
        "Castanets",
        "Belltree",
        "Jingle Bell",
        "Shaker",
        "Open Triangle",
        "Mute Triangle",
        "Open Cuica",
        "Mute Cuica",
        "Low Woodblock",
        "High Woodblock",
        "Claves",
        "Long Guiro",
        "Short Guiro",
        "Long Lo Whistle",
        "Short Hi Whistle",
        "Maracas",
        "Cabasa",
        "Low Agogo",
        "High Agogo",
        "Low Timbale",
        "High Timbale",
        "Low Conga",
        "Open Hi Conga",
        "Mute Hi Conga",
        "Low Bongo",
        "High Bongo",
        "Ride Cymbal 2",
        "Vibra-Slap",
        "Crash Cymbal 2",
        "Cowbell",
        "Splash Cymbal",
        "Tambourine",
        "Ride Bell",
        "Chinese Cymbal",
        "Ride Cymbal",
        "High Tom 1",
        "Crash Cymbal",
        "High Tom 2",
        "Mid Tom 1",
        "Open Hi-Hat",
        "Mid Tom 2",
        "Pedal Hi-Hat",
        "Low Tom 1",
        "Closed Hi-Hat",
        "Low Tom 2",
        "Snare Drum 2",
        "Hand Clap",
        "Snare Drum 1",
        "Side Stick",
        "Kick Drum 1",
        "Kick Drum 2",
        "Metronome Bell",
        "Metronome Click",
        "Square Click",
        "Sticks",
        "Scratch Pull",
        "Scratch Push",
        "Slap",
        "High Q"
    ],
    "percussion_808": [
        "Click",
        "High Tom",
        "808 Cowbell",
        "Mid Tom 1",
        "Mid Tom 2",
        "Low Tom 1",
        "Low Tom 2",
        "808 Cymbal",
        "Open Hi-Hat",
        "Closed Hi-Hat",
        "Snare Click",
        "Snare Drum 1",
        "Snare Drum 2",
        "Hand Clap 1",
        "Hand Clap 2",
        "Kick Drum 1",
        "Kick Drum 2",
        "Kick Drum 3"
    ],
    "percussion_8bit": [
        "Snare Drum 1",
        "Snare Drum 2",
        "Snare Drum 3",
        "Hi-Hat",
        "Snare Drum 4",
        "Kick Drum"
    ],
    "percussion_2013": [
        "Snare Drum 6",
        "Crash Cymbal 4",
        "Snare Drum 5",
        "Ride Bell 2",
        "Ride Cymbal 2",
        "Crash Cymbal 3",
        "Cowbell",
        "Splash Cymbal",
        "Tambourine",
        " Ride Bell 1",
        "Crash Cymbal 2",
        "Ride Cymbal 1",
        "Mid Tom 2",
        "Crash Cymbal 1",
        "Mid Tom 1",
        " Low Tom 4",
        "Loose Hi-Hat",
        " Low Tom 3",
        "Open Hi-Hat",
        " Low Tom 2",
        "Closed Hi-Hat",
        "Low Tom 1",
        "Snare Drum 4",
        "Snare Drum 3",
        "Snare Drum 2",
        "Snare Drum 1",
        "Kick Drum 2",
        "Kick Drum"
    ],
    "percussion_909": [
        "Ride Cymbal",
        "Crash Cymbal",
        "Open Hi-Hat 1",
        "Open Hi-Hat 2",
        "Closed Hi-Hat 1",
        "Closed Hi-Hat 2",
        "Clap",
        "Rim",
        "High Tom 1",
        "High Tom 2",
        "Mid Tom 1",
        "Mid Tom 2",
        "Low Tom 1",
        "Low Tom 2",
        "Snare Drum 1",
        "Snare Drum 2",
        "Snare Drum 3",
        "Kick Drum 1",
        "Kick Drum 2",
        "Kick Drum 3",
        "a"
    ],
    "percussion_2023": [
        "Marimba C6",
        "Marimba C5",
        "Marimba C4",
        "Orchestra Hit C5",
        "Timpani C5",
        "Timpani A4",
        "Timpani F4",
        "Belltree",
        "Vibraslap",
        "Krin 3",
        "Krin 2",
        "Krin 1",
        "Djembe Slap 3",
        "Djembe Slap 2",
        "Djembe Slap 1",
        "Djembe Tone 2",
        "Djembe Tone 1",
        "Djembe Bass",
        "Chenda Low",
        "Chenda High",
        "Udu Tin",
        "Udu Ta",
        "Tabla Ti",
        "Tabla Ghran",
        "Tabla Ghe",
        "Mridangam Nam",
        "Mridangam Thom",
        "Low Agogo",
        "High Agogo",
        "Low Timbale",
        "High Timbale",
        "Low Conga",
        "High Conga",
        "Mute Conga",
        "Low Bongo",
        "High Bongo",
        "Triangle",
        "Bell",
        "Jingle Bells",
        "Tambourine",
        "Clash Cymbals",
        "Splash Cymbal 2",
        "Splash Cymbal 1",
        "Ride Bell 2",
        "Ride Bell 1",
        "Ride Cymbal 2",
        "Ride Cymbal 1",
        "Crash Cymbal 3",
        "Crash Cymbal 2",
        "Crash Cymbal 1",
        "Hi-hat Splash",
        "Hi-hat Pedal",
        "Hi-hat Open",
        "Hi-hat Closed",
        "High Tom 2",
        "Mid Tom 2",
        "Low Tom 2",
        "High Tom",
        "Mid Tom",
        "Low Tom",
        "Snare Buzz",
        "Snare Brush",
        "Snare Rim Shot",
        "Snare 2",
        "Snare 1",
        "Snare Side Stick",
        "Kick 4",
        "Kick 3",
        "Kick 2",
        "Kick 1",
        "Bass Drum",
        "Sticks"
    ],
    "username": "Lastie",
    "uid": 95289,
    "logoutkey": "9bb36b7300791abeb67ed475c07eb493",
    "offline": false,
    "sampleSize": {
        "church_reverb.ogg": 81791,
        "classic_reverb.ogg": 78279,
        "gated_reverb.ogg": 38987,
        "large_reverb.ogg": 118362,
        "miasma.ogg": 147053,
        "nova.ogg": 172961,
        "proton.ogg": 292025,
        "reverse.ogg": 26261,
        "ripple.ogg": 228765,
        "schema.ogg": 119161,
        "short_reverb.ogg": 28045,
        "small_reverb.ogg": 24496,
        "sylph.ogg": 144917,
        "0.mp3": 995406,
        "1.mp3": 1280853,
        "10.mp3": 535310,
        "11.mp3": 408490,
        "12.mp3": 460530,
        "17.mp3": 995322,
        "18.mp3": 995852,
        "19.mp3": 420466,
        "2.mp3": 2897667,
        "20.mp3": 614313,
        "21.mp3": 447742,
        "22.mp3": 707715,
        "23.mp3": 1087523,
        "24.mp3": 1016730,
        "25.mp3": 458646,
        "26.mp3": 580144,
        "27.mp3": 1085433,
        "28.mp3": 1512847,
        "29.mp3": 620250,
        "3.mp3": 1153009,
        "30.mp3": 1301883,
        "31.mp3": 578076,
        "32.mp3": 491099,
        "33.mp3": 525740,
        "34.mp3": 594423,
        "35.mp3": 551893,
        "36.mp3": 264862,
        "37.mp3": 334896,
        "38.mp3": 934699,
        "39.mp3": 55280,
        "4.mp3": 455400,
        "40.mp3": 1365382,
        "42.mp3": 573187,
        "5.mp3": 334221,
        "53.mp3": 4719118,
        "6.mp3": 1153009,
        "7.mp3": 613180,
        "8.mp3": 1311017,
        "9.mp3": 409267,
        "0.ogg": 912533,
        "1.ogg": 950108,
        "10.ogg": 673595,
        "11.ogg": 546599,
        "12.ogg": 531392,
        "17.ogg": 984223,
        "18.ogg": 957194,
        "19.ogg": 656664,
        "2.ogg": 495102,
        "20.ogg": 1277545,
        "21.ogg": 870674,
        "22.ogg": 1112728,
        "23.ogg": 1127851,
        "24.ogg": 963439,
        "25.ogg": 638273,
        "26.ogg": 974380,
        "27.ogg": 1094656,
        "28.ogg": 1566455,
        "29.ogg": 1074709,
        "3.ogg": 1008282,
        "30.ogg": 1203396,
        "31.ogg": 983454,
        "32.ogg": 569566,
        "33.ogg": 763515,
        "34.ogg": 894336,
        "35.ogg": 765194,
        "36.ogg": 201035,
        "37.ogg": 474233,
        "38.ogg": 1340951,
        "39.ogg": 41819,
        "4.ogg": 732685,
        "40.ogg": 972645,
        "42.ogg": 320221,
        "5.ogg": 472132,
        "53.ogg": 4135026,
        "6.ogg": 1098883,
        "7.ogg": 600258,
        "8.ogg": 1529726,
        "9.ogg": 510484,
        "41.mp3": 2951997,
        "43.mp3": 2641439,
        "44.mp3": 4327677,
        "45.mp3": 1353856,
        "46.mp3": 3612974,
        "47.mp3": 5230257,
        "48.mp3": 4435661,
        "49.mp3": 4122610,
        "50.mp3": 1017992,
        "51.mp3": 1141904,
        "52.mp3": 3663595,
        "54.mp3": 859184,
        "55.mp3": 0,
        "56.mp3": 3924719,
        "57.mp3": 5340451,
        "41.ogg": 2699806,
        "43.ogg": 2047852,
        "44.ogg": 2911750,
        "45.ogg": 3540930,
        "46.ogg": 3438297,
        "47.ogg": 4860437,
        "48.ogg": 734268,
        "49.ogg": 5735069,
        "50.ogg": 655451,
        "51.ogg": 880138,
        "52.ogg": 3362986,
        "54.ogg": 1013033,
        "55.ogg": 0,
        "56.ogg": 3036031,
        "57.ogg": 3895110
    },
    "numNotes": 72,
    "numInstruments": 58,
    "instrumentDisplayOrder": [
        43,
        41,
        17,
        25,
        26,
        0,
        8,
        2,
        31,
        19,
        34,
        21,
        39,
        40,
        36,
        42,
        53,
        1,
        4,
        48,
        54,
        5,
        29,
        32,
        35,
        38,
        44,
        49,
        22,
        33,
        52,
        6,
        7,
        13,
        14,
        15,
        16,
        30,
        57,
        27,
        56,
        37,
        9,
        50,
        10,
        51,
        11,
        46,
        12,
        45,
        18,
        20,
        23,
        47,
        24,
        28
    ],
    "post_key": "1e8d8330b7ccd4818a34427f379b59dd",
    "user": {
        "shortcuts": "",
        "disable_webgl": "false",
        "remember_length": "true",
        "remember_volume": "true",
        "custom_cursor": "false"
    }
};

$.ajax('/ajax/update_playlist.php', {
    type: 'POST', data: {
    id: id, add_sequence:
    sequenceId, post_key:
    settings.post_key} });
}



function removeNonNumericCharacters(id) {
    return id.replace(/[^0-9]/g, '');
}

function updateMessageCountAndIds() {
    let songId = 0;
    const elements = document.querySelectorAll('.chat');
    const count = elements.length;
    const idList = Array.from(elements).map((element) => element.id);
    const cleanedIds = idList.map(removeNonNumericCharacters);
    const latestMessage = 'chat-' + cleanedIds[cleanedIds.length - 1];
    if (latestMessage !== previousId) {
        console.log(`Latest Message ID is ${latestMessage}`);
        const parent = document.querySelector(`#${latestMessage}`);
        let child = parent.querySelector('.info');
        if (child !== null) {
            child = child.querySelector('div');
        } else if (child === null) {
            child = parent.querySelector('div');
        }

        const child2 = child.querySelector('.message');
        const message = child2.innerText;
        let hasSequence = child2.querySelector('a');
        let imgLocation = hasSequence;


        if (hasSequence !== null && message !== null) {
            hasSequence = hasSequence.href;
            if (hasSequence.includes("https://onlinesequencer.net/") || hasSequence.includes("https://test.onlinesequencer.net/")) {
                console.log('yes');
                    songId = removeNonNumericCharacters(hasSequence);
            }
            console.log(message + hasSequence);
        } if (hasSequence === null) {
            console.log(message);
            if (message.includes('https://onlinesequencer.net/' || message.includes("https://test.onlinesequencer.net/"))) {
                songId = removeNonNumericCharacters(message);
                console.log('yes');
            }
            console.log(hasSequence);
        } if (message === null && hasSequence === null) {
            console.log('No message found!')
        }
        if (songId !== 0){
            console.log('image url: ','https://onlinesequencer.net/preview.php?id='+songId);
            if (hasSequence.includes('https://test.onlinesequencer.net/')){
                const imgSrc = 'https://onlinesequencer.net/preview.php?id='+songId;
                // Create an image element
                const imgElement = document.createElement("img");
                imgElement.src = imgSrc;
                imgLocation.innerText = '';

                // Insert the image element after the reference element
                imgLocation.appendChild(imgElement);


            }
            addToPlaylist(30876, songId)
        }
    }
    previousId = latestMessage;
    return cleanedIds;
}

let previousId = 0;
setInterval(updateMessageCountAndIds, 100);